### ISSUE TITLE
"build your car" vs "get a quote" 

### ISSUE THREAD

**Issue by pavoni** [pavoni/private-issues#9]
- Some of the buttons "Build your car", some say "Get a quote"

**Comment by vsoheilbron** [comment]
Picture of Browse Cars page where the buttons of the cars say "Get a quote". These should all say "Build your car".

I tried to find these buttons in Drupal to make the changes myself, but it looks like they're fed in from the API. Depending on from what side the information is fed into the API, this could be a Marmalade or a DigitalLabs question

![image](https://user-images.githubusercontent.com/59653880/71986899-2722eb00-3225-11ea-90a2-0c1b78a17da3.png)

**Comment by pavoni** [comment]
Fixed by digital labs
